logicFunctions = ("ADD", "SUB", "MULT", "DIV", "MOD", "POWER", "GREATER", 
                "LESS", "MIN", "MAX", "ABS", "SIGN", "ROUND", "CEIL",
                "FLOOR", "SQRT", "dSIN", "dASIN", "dCOS", "dACOS", "dTAN",
                "dATAN", "rSIN", "rASIN", "rCOS", "rACOS", "rTAN", "rATAN")

functionsWithTwoInputs = ("ADD", "SUB", "MULT", "DIV", "MOD", "POWER", "GREATER",
                          "LESS", "MIN", "MAX")

functionToBRName = {
    "ADD": "Add",
    "SUB": "Subtract",
    "MULT": "Multiply",
    "DIV": "Divide",
    "MOD": "Fmod",
    "POWER": "Power",
    "GREATER": "Greater",
    "LESS": "Less",
    "MIN": "Min",
    "MAX": "Max",
    "ABS": "Abs",
    "SIGN": "Sign",
    "ROUND": "Round",
    "CEIL": "Ceil",
    "FLOOR": "Floor",
    "SQRT": "Sqrt",
    "dSIN": "SinDeg",
    "rSIN": "Sin",
    "SIN": "Sin",
    "dCOS": "CosDeg",
    "rCOS": "Cos",
    "COS": "Cos",
    "dTAN": "TanDeg",
    "rTAN": "Tan",
    "TAN": "Tan",
    "dASIN": "AsinDeg",
    "rASIN": "Asin",
    "ASIN": "Asin",
    "dACOS": "AcosDeg",
    "rACOS": "Acos",
    "ACOS": "Acos",
    "dATAN": "AtanDeg",
    "rATAN": "Atan",
    "ATAN": "Atan"
}